name: vktest
on: 
  push:
    branches: master

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    name: main on ${{ matrix.os }}
    steps:
    - name: try installing lunar upstream on ${{ matrix.os }}
      run: |
        wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.1.126-bionic.list http://packages.lunarg.com/vulkan/1.1.126/lunarg-vulkan-1.1.126-bionic.list
        sudo apt update
        sudo apt install vulkan-sdk
